### ISSUE TITLE
Från Daniel V.

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_EonDiceRoller#1]
Hej Johan, jag testade din modul till Foundry, fungerade bra! Bra jobbat, jag undrar, finns de några macro kommandon man kan använda? För att t.ex slå lite lättare än klicka manuellt flera gånger på T6:an ? 

Hade varit skönt om man kunde förprogrammera tärningslag, t.ex 3T6+2 osv..

**Comment by JohanFalt** [comment]
Hade det "räckt" om man direkt kunna klicka på t ex en 5-knapp? Där man kan välja hur många tärningar man vill slå men en tryckning?

**Comment by Thalaski** [comment]
![OB-tärningsDIal](https://github.com/JohanFalt/Foundry_EonDiceRoller/assets/101973274/83f973b3-89be-4719-81a6-0b3a69db234d)
Nu kanske jag är lite sen till festen, men jag ffunderar på om någonting sånt här skulle kunna funka? Att om man håller in musknappen längre än typ 500ms så öppnar man en radial meny med 1-10, drar man utanför den menyn så kommer man upp i 11-20 osv. När man släpper musknappen så väljs det som man just då hovrar över. 

Det borde resultera i att det både är enkelt och går snabbt att välja antalet tärningar.

**Comment by JohanFalt** [comment]
Var ju ett ellegant utseende, inte riktigt säker på hur att man skall koda in det. Får se vad jag kan göra.

**Comment by Thalaski** [comment]
Tänker att någotning typ sånt här skulle kunna funka:
Alt 1: https://codepen.io/web-tiki/pen/ZYmZoV/
Alt 2: https://codepen.io/CreativePunch/pen/wvwQer
Alt3: https://tympanus.net/codrops/2013/08/09/building-a-circular-navigation-with-css-transforms/

Det skulle ju också funka att bara få upp en rad.

**Comment by JohanFalt** [comment]
Det riktigt snyggt och enkelt. Ska testa att få ihop en  lösning i en eller två cirkel.

**Comment by JohanFalt** [comment]
Detta blir slutresultatet. Du helt enkelt klickar på siffran för att få vad du vill ha. Så vill man ha 15 tärningar så trycker man på 1 + 5.

![image](https://github.com/JohanFalt/Foundry_EonDiceRoller/assets/57871596/743b7561-7a4b-4f75-85b5-610b3d7a6c38)

![image](https://github.com/JohanFalt/Foundry_EonDiceRoller/assets/57871596/e6dbf785-37ff-4a58-bd7a-ec7e284323fb)

**Comment by JohanFalt** [comment]
Nä det funkade inte bra alls. Snyggt men rutor som hamnade utanför skärmen etc. Så jag gör en mycket enklare lösning:

![image](https://github.com/JohanFalt/Foundry_EonDiceRoller/assets/57871596/81d7b582-d88d-4b07-a109-910e1531b22e)

**Comment by JohanFalt** [comment]
Inlagt i v1.2
