### ISSUE TITLE
BUG EonDiceRoller slutade att fungera tillsammans med Simple World Building

### ISSUE THREAD

**Issue by Thalaski** [JohanFalt/Foundry_EonDiceRoller#4]
Av någon anledning så slutade modulen att fungera tillsammans med systemet Simple World Building vid en uppdatering av Core. Att avaktivera och återaktivera modulen funkar inte heller. Inte heller att installera om modulen. Antagligen ligger det något skräp som blockerar någonstans. Men jag har migrerat över allt vesentligt till en ny värld baserat på Eon-RPG där EonDiceRoller funkar. 

Bifigar loggfilen. 

[vtt.local-1690973895566.log](https://github.com/JohanFalt/Foundry_EonDiceRoller/files/12239338/vtt.local-1690973895566.log)

**Comment by JohanFalt** [comment]
Fixad i 1.4.1.

**Comment by Thalaski** [comment]
Fungerar nu
